from bson import ObjectId
from db import users_collection
from datetime import datetime


class User:
    def __init__(
        self,
        email,
        full_name,
        password,
        username=None,
        profile =None,
        preferences=None,
        email_verified=False,
        _id=None,
        created_at=None,
        updated_at=None
    ):
        self._id = ObjectId(_id) if _id else None
        self.full_name = full_name
        self.email = email
        self.username = username
        self.password = password
        self.profile = profile if profile else {"description": "", "links": []}
        self.preferences = preferences
        self.email_verified = email_verified
        self.created_at = created_at
        self.updated_at = updated_at

    def to_dict(self):
        """Convert User object to dictionary"""
        return {
            "_id": self._id,
            "full_name": self.full_name,
            "email": self.email,
            "username": self.username,
            "password": self.password,
            "profile": self.profile,
            "preferences": self.preferences,
            "email_verified": self.email_verified,
            "created_at": self.created_at,
            "updated_at" : self.updated_at
        }

    def to_json(self):
        """Convert User object to JSON-serializable dictionary"""
        return {
            "_id": str(self._id) if self._id else None,
            "full_name": self.full_name,
            "email": self.email,
            "username": self.username,
            "profile": self.profile,
            "preferences": self.preferences,
            "email_verified": self.email_verified,
            "created_at": str(self.created_at),
            "updated_at" : str(self.updated_at)
        
        }

    def create(self):
        """Create a new user"""
        try:
            user_data = self.to_dict()
            # Remove _id for creation, as it's generated by MongoDB
            if user_data.get("_id") is None:
                del user_data["_id"]

            user_data["created_at"] = datetime.now()

            result = users_collection.insert_one(user_data)
            self._id = result.inserted_id
            return str(result.inserted_id)
        except Exception as e:
            raise Exception(f"Failed to create user: {str(e)}")

    def update(self, updates):
        """Update an existing user"""
        if not self._id:
            raise ValueError("Cannot update user without _id")
        
        try:
            
            update_data = {k: v for k, v in updates.items() if v is not None}
            
            # Update object attributes
            for key, value in update_data.items():
                if hasattr(self, key):
                    setattr(self, key, value)
            
            update_data["updated_at"] = datetime.now()

            result = users_collection.update_one({"_id": self._id}, {"$set": update_data})
            return result.modified_count > 0
        except Exception as e:
            raise Exception(f"Failed to update user: {str(e)}")
    
    def delete(self):
        """Delete the user"""
        if not self._id:
            raise ValueError("Cannot delete user without _id")
        
        try:
            
            result = users_collection.delete_one({"_id": self._id})
            return result.deleted_count > 0
        except Exception as e:
            raise Exception(f"Failed to delete user: {str(e)}")
    
    @staticmethod
    def get_by_email(email):
        user = users_collection.find_one(filter={"email":email})
        if user:
            return User(**user)
        return None

    @staticmethod
    def get_by_id(user_id):
        user = users_collection.find_one(filter={"_id":ObjectId(user_id)})
        if user:
            return User(**user)
        return None

    @staticmethod
    def get_by_username(usernmae:str):
        user = users_collection.find_one(filter={"username":usernmae.strip()})
        if user:
            return User(**user)
        return None

    @staticmethod
    def verify_user_email(user_id:str):
        user = User.get_by_id(user_id=user_id)
        if not user.email_verified:
            return user.update({"email_verified":True})
        return True

    @staticmethod
    def is_username_exists(username:str):
        user = users_collection.find_one({"username":username})
        if user:
            return True
        return False